# Generated by Django 3.2.7 on 2021-10-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tejido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'tablaValores',
                'verbose_name_plural': 'tablaValores',
            },
        ),
    ]
