# Generated by Django 3.2.7 on 2021-10-15 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211015_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tessiu',
            options={'verbose_name': 'Tessiu', 'verbose_name_plural': 'Tessius'},
        ),
    ]
