# Generated by Django 3.2.7 on 2021-11-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_tessiu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tessiu',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
